apiVersion: v1
kind: Service
metadata:
  name: cloudlaunch-api
  namespace: cloudlaunch
  labels:
    app.kubernetes.io/name: cloudlaunch-api
spec:
  type: ClusterIP
  selector:
    app: cloudlaunch-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
